### ISSUE TITLE
怎么用的？

### ISSUE THREAD

**Issue by live17909** [hui-z/bluetooth_print_plugin#1]
怎么用的？

>

**Comment by 123lxw123** [comment]
这个原本是想要写个 Flutter 蓝牙连接库，但是根据复杂度和项目进度综合考虑后，还是 fork [flutter_blue](https://github.com/pauldemarco/flutter_blue) 这个开源库进行修改使用。稍后会删掉这个项目。

**Comment by live17909** [comment]
保留也没事哈。。
